{% set name = "google-cloud-compute" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b637c4b1455584473fbdd41f8a38660c5b51cb69bfc70978eeb44b7d371e5e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - google-api-core-grpc >=2.2.0,<3.0.0dev
    - proto-plus >=1.19.7

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.compute
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-compute
  summary: Python Client for Google Cloud Compute Engine
  doc_url: https://googleapis.dev/python/compute/latest/index.html
  dev_url: https://github.com/googleapis/python-compute
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
