{% set name = "google-cloud-compute" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1be91360829440670a898cfb39a01e6cd88444e709f9db11e27d48670971632c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

# an additional runtime dependency of dataclasses is necessary for Python 3.6,
# conda-forge stopped building 3.6 so we impose a 3.7 requirement to prevent
# upgrades of older systems
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - google-api-core-grpc >=2.8.0,<3.0.0dev
    - proto-plus >=1.19.7,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.compute
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-compute
  summary: Python Client for Google Cloud Compute Engine
  doc_url: https://googleapis.dev/python/compute/latest/index.html
  dev_url: https://github.com/googleapis/python-compute
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
